input_helper:
    mode: off
    name: whitelistcounter
    encoding: UTF-8
    in_encoding: cp1252
    whitelist: domains/lotr/data/whitelist.txt
    input_directory: domains/lotr/data/rawtext
    threads: 1
    out_config: 
        together: # puts everything into one big json dictionary in the same json file
            mode: on
            outfile: domains/lotr/out/mm_input.json
        separated: # divides the three main input components into three files. see below
            mode: on
            outfile_global_tokens: domains/lotr/out/global_tokens.json # stem_to_id, id_to_repr_token
            outfile_global_counts: domains/lotr/out/global_counts.json
            outfile_doc_counts: domains/lotr/out/mm_doc_counts.json
            outfile_representative_tokens: domains/lotr/out/synonyms.json


    #docs_metadata: domains/lotr/data/doc_meta.json

legacy_helper:
    mode: off
    input_json_file: domains/lotr/out/mm_input.json
    output_dir: domains/lotr/out/legacy/query_result/
    doc_metadata: domains/lotr/data/doc_meta.json
    num_timeslices: 10
    output_json: &score_JSON domains/lotr/out/legacy_handler_out.json
    options:
        choose_representative_token: on

scoring_helper:
    mode: off
    name: tfidf
    input_json_file: domains/lotr/out/mm_input.json
    output_dir: domains/lotr/out/legacy/query_result/
    doc_metadata: domains/lotr/data/doc_meta.json
    num_timeslices: 10
    output_json: domains/lotr/out/legacy_handler_out.json

clustering:
    mode: on
    input_json = *score_JSON 
    output_json = &clusters_JSON 
